/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.VeiculoController;
/**
 *
 * @author mario
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public TelaInicial() {
        this.initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuEditar = new javax.swing.JMenu();
        menuVeiculo = new javax.swing.JMenu();
        itemMenuVeiculoCadastrar = new javax.swing.JMenuItem();
        itemMenuVeiculoConsultar = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        itemMenuClienteCadastrar = new javax.swing.JMenuItem();
        itemMenuClienteConsultar = new javax.swing.JMenuItem();
        menuPropostas = new javax.swing.JMenu();
        itemMenuPropostasCadastrar = new javax.swing.JMenuItem();
        itemMenuPropostasConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venda de Carros");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/venda-de-carros.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuArquivo.setText("Arquivo");
        jMenuBar1.add(menuArquivo);

        menuEditar.setText("Editar");
        jMenuBar1.add(menuEditar);

        menuVeiculo.setMnemonic('v');
        menuVeiculo.setText("Veiculo");

        itemMenuVeiculoCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuVeiculoCadastrar.setMnemonic('a');
        itemMenuVeiculoCadastrar.setText("Cadastrar");
        itemMenuVeiculoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVeiculoCadastrarActionPerformed(evt);
            }
        });
        menuVeiculo.add(itemMenuVeiculoCadastrar);

        itemMenuVeiculoConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuVeiculoConsultar.setMnemonic('o');
        itemMenuVeiculoConsultar.setText("Consultar");
        itemMenuVeiculoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVeiculoConsultarActionPerformed(evt);
            }
        });
        menuVeiculo.add(itemMenuVeiculoConsultar);

        jMenuBar1.add(menuVeiculo);

        menuCliente.setMnemonic('c');
        menuCliente.setText("Cliente");

        itemMenuClienteCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuClienteCadastrar.setMnemonic('a');
        itemMenuClienteCadastrar.setText("Cadastrar");
        itemMenuClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClienteCadastrarActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuClienteCadastrar);

        itemMenuClienteConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuClienteConsultar.setMnemonic('o');
        itemMenuClienteConsultar.setText("Consultar");
        itemMenuClienteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClienteConsultarActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuClienteConsultar);

        jMenuBar1.add(menuCliente);

        menuPropostas.setMnemonic('p');
        menuPropostas.setText("Propostas");

        itemMenuPropostasCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuPropostasCadastrar.setMnemonic('a');
        itemMenuPropostasCadastrar.setText("Cadastrar");
        itemMenuPropostasCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuPropostasCadastrarActionPerformed(evt);
            }
        });
        menuPropostas.add(itemMenuPropostasCadastrar);

        itemMenuPropostasConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuPropostasConsultar.setMnemonic('o');
        itemMenuPropostasConsultar.setText("Consultar");
        menuPropostas.add(itemMenuPropostasConsultar);

        jMenuBar1.add(menuPropostas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1886, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuVeiculoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVeiculoCadastrarActionPerformed
        TelaCadastroVeiculo tela = new TelaCadastroVeiculo();
        
        tela.setVisible(true);
    }//GEN-LAST:event_itemMenuVeiculoCadastrarActionPerformed

    private void itemMenuVeiculoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVeiculoConsultarActionPerformed
        TelaConsultaVeiculo tela = new TelaConsultaVeiculo();
        
        tela.setVisible(true);
    }//GEN-LAST:event_itemMenuVeiculoConsultarActionPerformed

    private void itemMenuClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClienteCadastrarActionPerformed
        TelaCadastroCliente tela = new TelaCadastroCliente();
        
        tela.setVisible(true);
    }//GEN-LAST:event_itemMenuClienteCadastrarActionPerformed

    private void itemMenuClienteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClienteConsultarActionPerformed
        TelaConsultaCliente tela = new TelaConsultaCliente();
        
        tela.setVisible(true);
    }//GEN-LAST:event_itemMenuClienteConsultarActionPerformed

    private void itemMenuPropostasCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuPropostasCadastrarActionPerformed
        TelaCadastroProposta tela = new TelaCadastroProposta();
        
        tela.setVisible(true);
    }//GEN-LAST:event_itemMenuPropostasCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuClienteCadastrar;
    private javax.swing.JMenuItem itemMenuClienteConsultar;
    private javax.swing.JMenuItem itemMenuPropostasCadastrar;
    private javax.swing.JMenuItem itemMenuPropostasConsultar;
    private javax.swing.JMenuItem itemMenuVeiculoCadastrar;
    private javax.swing.JMenuItem itemMenuVeiculoConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuPropostas;
    private javax.swing.JMenu menuVeiculo;
    // End of variables declaration//GEN-END:variables
}
