/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.VeiculoController;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Veiculo;
import static view.FrameVeiculo.*;


/**
 *
 * @author aluno
 */
public class TelaVeiculo extends javax.swing.JFrame {
    VeiculoController veiculoController = new VeiculoController();
    public TelaVeiculo() {
        initComponents();
        txtLocalFoto.setVisible(false);
        lblLocalFoto.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        veiculo1 = new view.FrameVeiculo();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Filtrar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(veiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(veiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultar)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Veiculo v = veiculoController.getVeiculo(FrameVeiculo.txtModelo.getText());
        
        if (v == null){
            JOptionPane.showMessageDialog(null, "Veículo não localizado!!", "Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            cmbMarca.setSelectedItem(v.getMarca());
            txtModelo.setText(v.getModelo());
            txtAno.setText(Integer.toString(v.getAno()));
            cmbCor.setSelectedItem(v.getCor());
            cmbTransmissao.setSelectedItem(v.getTransmissao());
            txtMotor.setText(v.getMotor());
            txtPlaca.setText(v.getPlaca());
            txtRenavam.setText(Long.toString(v.getRenavam()));
            txtChassi.setText(v.getChassi());
            txtValorCompra.setText(Double.toString(v.getValorCompra()));
            txtOdometro.setText(Integer.toString(v.getOdometro()));
            
            if (v.isDisponivel()){
                rdDisponivelNao.setSelected(false);
                rdDisponivelSim.setSelected(true);
            }else{
                rdDisponivelNao.setSelected(true);
                rdDisponivelSim.setSelected(false);
                
            }
            
            cmbCategoria.setSelectedItem(v.getCategoria());
            chkArCondicionado.setSelected(v.isArCondicionado());
            chkABS.setSelected(v.isAbs());
            chkTetoSolar.setSelected(v.isTetoSolar());
            chkKitEletrico.setSelected(v.isKitEletrico());
            chkBancoCouro.setSelected(v.isBancoCouro());
            chkDirecaoHidraulica.setSelected(v.isDirecaoHidraulica());
            chkFarolMilha.setSelected(v.isFarolMilha());
            chkCentralMultimidia.setSelected(v.isCentralMultimidia());
            chkPilotoAutomatico.setSelected(v.isPilotoAutomatico());
            chkLuzDiurna.setSelected(v.isLuzDiurna());
            chkComandoVolante.setSelected(v.isComandoVolante());
            chkAirBag.setSelected(v.isAirBag());
            //txtLocalFoto.setText(v.getNomeImagem());
            
            lblFoto.setIcon(new ImageIcon(getClass().getResource("/fotosCarros/" + v.getNomeImagem())));
        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        FrameVeiculo.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        Veiculo v = veiculoController.getVeiculo(FrameVeiculo.txtModelo.getText());
        
        
        if (v == null){
            JOptionPane.showMessageDialog(null, "Veículo não localizado!!", "Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            
            Veiculo veiculo = new Veiculo();
            
            veiculo.setMarca(cmbMarca.getSelectedItem().toString());
            veiculo.setModelo(txtModelo.getText());
            veiculo.setAno(Integer.parseInt(txtAno.getText()));
            veiculo.setCor(cmbCor.getSelectedItem().toString());
        System.out.println("Passei 0");
            veiculo.setTransmissao(cmbTransmissao.getSelectedItem().toString());
            veiculo.setMotor(txtMotor.getText());
            veiculo.setPlaca(txtPlaca.getText());
            veiculo.setRenavam(Long.parseLong(txtRenavam.getText()));
            veiculo.setChassi(txtChassi.getText());
            veiculo.setValorCompra(Double.parseDouble(txtValorCompra.getText()));
            veiculo.setOdometro(Integer.parseInt(txtOdometro.getText()));
            veiculo.setDisponivel(chkDirecaoHidraulica.isSelected());
            veiculo.setCategoria(cmbCategoria.getSelectedItem().toString());
            veiculo.setArCondicionado(chkArCondicionado.isSelected());
            System.out.println("Passei 1");
            veiculo.setAbs(chkABS.isSelected());
            veiculo.setTetoSolar(chkTetoSolar.isSelected());
            veiculo.setKitEletrico(chkKitEletrico.isSelected());
            veiculo.setBancoCouro(chkBancoCouro.isSelected());
            veiculo.setDirecaoHidraulica(chkDirecaoHidraulica.isSelected());
            veiculo.setFarolMilha(chkFarolMilha.isSelected());
            veiculo.setCentralMultimidia(chkCentralMultimidia.isSelected());
            veiculo.setPilotoAutomatico(chkPilotoAutomatico.isSelected());
            System.out.println("Passei 2");
            veiculo.setLuzDiurna(chkLuzDiurna.isSelected());
            veiculo.setComandoVolante(chkComandoVolante.isSelected());
            veiculo.setAirBag(chkAirBag.isSelected());
            
            System.out.println("Passei 10");
            
            veiculoController.alterarVeiculo(v, veiculo);
            
            JOptionPane.showMessageDialog(null, "Veículo alterado com sucesso!");
            
        }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private view.FrameVeiculo veiculo1;
    // End of variables declaration//GEN-END:variables
}
